# Site settings
title: Connie Young
email: conniemyou@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Hi! I’m Connie, a Multimedia designer based in South Texas with a passion for creating eye-catching social media content."
keywords: "portfolio, design, social media, multimedia, connie, connie young, connieyoung"
skills: "Multimedia Design - Production Art - Social Media"
meta_author: Young Connie

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 423E3E #80B3FF
  primary-rgb: "179,178,178" #"128,179,255"
  secondary: B3B2B2 #FD6E8A
  secondary-dark: 8b8a8a #A2122F
  tertiary: F7F6F5
  tertiary-dark: B3B2B2
  accent: 423E3E

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Contact
  social: Socials
  credits: Location

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: (210) 482-0803
  - line: conniemyou@gmail.com

# Credits content
credits: 'San Antonio, Texas'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
